import { motion } from "framer-motion";
import { Calendar, Car, MapPin } from "lucide-react";
import { Seo } from "@/components/Seo";

const sections = [
  { title: "Why Rent a Car in Srinagar?", content: "Kashmir is best experienced beyond the main city. A rental car gives you the freedom to create your own itinerary, travel comfortably with family or friends, keep your luggage with you, stop at scenic locations, and avoid depending on taxi timings.", items: ["Freedom to create your own itinerary", "Privacy and comfortable travel", "Stop at scenic locations whenever you like", "Easy access to destinations outside Srinagar"] },
  { title: "Self-Drive vs Chauffeur-Driven Car", content: "A self-drive car is ideal for travellers who enjoy driving, want privacy, prefer flexible schedules, and are comfortable on mountain roads. A chauffeur-driven car can be more suitable if you prefer someone else to handle the drive or are unfamiliar with mountain roads." },
  { title: "What Documents Do You Need?", content: "For self-drive rentals, keep a valid driving licence, government-issued identification, booking confirmation, and security deposit where applicable. Confirm insurance and the exact rental terms with your provider before booking." },
  { title: "What Type of Car Should You Rent?", content: "Hatchbacks suit Srinagar city, short trips, couples, and budget-conscious travellers. Sedans are comfortable for small families and highway journeys. SUVs are often preferable for longer mountain trips to Gulmarg, Pahalgam, Sonamarg, Doodhpathri, Gurez, and Ladakh because of their ground clearance and space." },
  { title: "Best Cars for a Kashmir Road Trip", content: "Choose more than the lowest daily price. Consider ground clearance for uneven roads, luggage space, seating comfort for long journeys, fuel economy, and whether you prefer an automatic or manual vehicle." },
  { title: "Popular Road Trips from Srinagar", content: "Srinagar is an excellent base for Gulmarg, Pahalgam, Sonamarg, Doodhpathri, and the longer Srinagar–Leh journey. A self-drive rental lets you experience each route at your own pace." },
  { title: "Srinagar Airport Car Rental", content: "Srinagar International Airport is approximately 15 km from central Srinagar. For airport pickup, share your flight number, arrival date, expected arrival time, and contact number. You can collect your vehicle, load your luggage, and start your journey directly." },
  { title: "How Much Does Car Rental in Srinagar Cost?", content: "Prices vary by car model, vehicle category, rental duration, season, availability, pickup and drop-off location, and rental terms. Clarify the daily rate, security deposit, fuel policy, mileage conditions, insurance, additional-day charges, and cancellation terms before booking." },
  { title: "When Should You Book?", content: "March to October is the peak tourist season. Book early if you need a premium SUV, airport pickup, a specific vehicle, or a longer rental during busy travel periods." },
  { title: "Tips for Driving in Kashmir", content: "Avoid unnecessary night driving, drive according to rain, snow, fog, and visibility, and never overtake on blind curves.", items: ["Keep your fuel level comfortable on remote routes", "Check weather before long drives", "Carry offline maps", "Keep your driving licence and ID accessible"] },
  { title: "What Should You Check Before Accepting the Rental Car?", content: "Inspect the exterior, tyres, lights, mirrors, windscreen, fuel level, spare tyre, brakes, and existing scratches or dents. Take photographs before departure and understand the roadside-assistance process." },
];

export default function CarRentalSrinagarGuide() {
  return <div className="min-h-screen bg-slate-50 pt-24 pb-16"><Seo title="Car Rental in Srinagar: Complete Guide for Tourists" description="Looking for car rental in Srinagar? Learn about self-drive cars, rental prices, documents, airport pickup, best cars and tips for exploring Kashmir." path="/blog/car-rental-in-srinagar" ogType="article" /><article>
    <section className="relative overflow-hidden border-b border-slate-200 bg-slate-950 text-white"><div className="absolute inset-0"><img src="https://images.unsplash.com/photo-1500534623283-312aade485b7?q=80&w=1920&auto=format&fit=crop" alt="Scenic Kashmir mountain road near Srinagar" loading="lazy" className="h-full w-full object-cover opacity-35" /><div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-primary/85 to-slate-900/60" /></div><div className="container relative mx-auto px-4 py-16 md:px-6 md:py-24"><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="max-w-4xl"><div className="mb-5 flex flex-wrap gap-3 text-sm font-semibold text-white/85"><span className="inline-flex items-center gap-2 rounded-full bg-white/12 px-3 py-1.5 backdrop-blur"><Calendar size={16} /> Car Rental Guide</span><span className="inline-flex items-center gap-2 rounded-full bg-white/12 px-3 py-1.5 backdrop-blur"><MapPin size={16} /> Srinagar, Kashmir</span></div><h1 className="text-4xl font-display font-bold leading-tight md:text-6xl">Car Rental in Srinagar: Everything Tourists Need to Know</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/90 md:text-xl">Plan a flexible, comfortable Kashmir road trip from Srinagar with confidence.</p></motion.div></div></section>
    <section className="container mx-auto px-4 py-12 md:px-6 md:py-16"><div className="mx-auto max-w-4xl space-y-8"><section className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm md:p-8"><p className="leading-7 text-slate-700">Planning a trip to Kashmir and wondering about the best way to get around? <strong>Car rental in Srinagar</strong> is one of the most convenient options for travellers who want flexibility, comfort, and the freedom to explore beyond the usual tourist routes.</p><p className="mt-4 leading-7 text-slate-700">From Srinagar, you can plan road trips to <strong>Gulmarg, Pahalgam, Sonamarg, Doodhpathri, Yusmarg</strong>, and other destinations across the valley. Car rental services are available at Srinagar Airport and within the city, including self-drive options.</p></section>{sections.map((section) => <section key={section.title} className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm md:p-8"><h2 className="text-2xl font-display font-bold text-primary">{section.title}</h2><p className="mt-4 leading-7 text-slate-700">{section.content}</p>{section.items && <ul className="mt-4 list-disc space-y-2 pl-5 text-slate-700">{section.items.map((item) => <li key={item}>{item}</li>)}</ul>}</section>)}<section className="rounded-lg bg-primary p-6 text-white shadow-lg md:p-8"><h2 className="text-2xl font-display font-bold">Plan Your Kashmir Road Trip with Self Steer</h2><p className="mt-4 leading-7 text-white/90">Whether you&apos;re arriving at Srinagar Airport, exploring the city, or heading to Gulmarg, Pahalgam, Sonamarg, Doodhpathri, Gurez, or Ladakh, choose a vehicle that matches your route, group size, and driving experience.</p><p className="mt-5 font-semibold tracking-wide">Choose your car. Take the wheel. Create your journey.</p></section><section className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm md:p-8"><h2 className="text-2xl font-display font-bold text-primary">Frequently Asked Questions</h2><div className="mt-4 space-y-4 leading-7 text-slate-700"><p><strong>Can I rent a self-drive car in Srinagar?</strong> Yes. A valid driving licence is required, and rental providers may have additional requirements.</p><p><strong>Can I collect a rental car from Srinagar Airport?</strong> Yes. Advance coordination is recommended, especially during busy periods.</p><p><strong>Which car is best for Kashmir?</strong> Smaller cars suit city travel; SUVs are often more comfortable for long mountain journeys and extra luggage.</p><p><strong>Should I book in advance?</strong> Yes, particularly in peak season or if you want a specific vehicle.</p></div></section></div></section>
  </article></div>;
}
